apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sleep", "3600"]

      # Load secrets as environment variables
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD

      # Mount secrets as files
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true

      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"

  volumes:
    - name: secret-volume
      secret:
        secretName: app-secrets
        # File permissions (octal)
        defaultMode: 0400
