# PersistentVolumeClaim requests storage from the cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  # Access modes:
  # - ReadWriteOnce (RWO): single node read-write
  # - ReadOnlyMany (ROX): many nodes read-only
  # - ReadWriteMany (RWX): many nodes read-write
  accessModes:
    - ReadWriteOnce

  # K3s default storage class
  storageClassName: local-path

  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sleep", "3600"]

      volumeMounts:
        - name: data
          mountPath: /data

      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
