# App of Apps pattern - manage multiple apps from one
# Update the repoURL to point to your own repository
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default

  source:
    # Change this to your repository URL
    repoURL: https://github.com/ian-b-stewart/k3s-lab.git
    targetRevision: HEAD
    path: week-05/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
