# ReplicaSets ensure N identical pods are running
# Deployments manage ReplicaSets - you rarely create these directly
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami-rs
  labels:
    app: whoami-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-rs
  template:
    metadata:
      labels:
        app: whoami-rs
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.10
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
