# CronJob runs Jobs on a schedule
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
spec:
  # Cron schedule (every minute for demo)
  # Format: minute hour day-of-month month day-of-week
  schedule: "*/1 * * * *"

  # Timezone (optional, requires K8s 1.27+)
  # timeZone: "America/New_York"

  # Keep last 3 successful jobs
  successfulJobsHistoryLimit: 3

  # Keep last 1 failed job
  failedJobsHistoryLimit: 1

  # What to do if a job is still running when next schedule hits
  # Allow, Forbid, or Replace
  concurrencyPolicy: Forbid

  # Job template
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.36
              command:
                - /bin/sh
                - -c
                - |
                  echo "==================================="
                  echo "Hello from CronJob!"
                  echo "Time: $(date)"
                  echo "Pod: $HOSTNAME"
                  echo "==================================="
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "50m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
